using Dotnet.Chroma.Repositories.Models.Enums;
using Dotnet.Chroma.Repositories.Models.Metadata;

namespace Dotnet.Chroma.Repositories.Models
{
    /// <summary>
    /// Base ABSTRACT class for all the sdk models / entities.
    /// Stores Identity and metadata, as well as the common helper methods
    /// </summary>
    public abstract class ChromaModel
    {
        public ChromaModel() 
        {
            Type = (int)EChunkType.DOCUMENT;

            Metadata = new Dictionary<string, object>() { [nameof(ChromaMetadata.TYPE).ToLower()] = (int)Type };

            setDefaultMetadata(); 
        }
        public ChromaModel(string id) : this() { Id = id; }
        public ChromaModel(string id, Dictionary<string, object> metadata) : this(id) 
        {
            Metadata = metadata; 
            
            setDefaultMetadata(); 
        }

        /// <summary>
        /// Chunk DB Identifier. String format because of chroma, it is:
        ///     > A string INT for al DOCUMENT chunks assigned from the collection TOTAL_CHUNKS metadata OR
        ///     > ID = 0 for all Collection Chunks OR
        ///     > The COLLECTION_GUID generated by Chroma (for ChormaCollection models)
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Default is COLLECTION (0) or DOCUMENT(1)
        /// Typed as int to allow extended classes with custom classifiers / enums
        /// </summary>
        public int Type { get; set; }
        /// <summary>
        /// Dictionary of chunk metadata tags from Chroma
        /// </summary>
        public Dictionary<string, object> Metadata { get; set; }

        /// <summary>
        /// Typed version of the Chroma Metadata dictionary that 'defines' the chunk and also makes it easier to work with it.
        /// </summary>
        public ChromaMetadata DefaultMetadata { get; set; }

        //Converts the stored int type to the required custom enum for extended classes
        // by default treats the chunk as a DOCUMENT chunk
        public TEnum ChunkType<TEnum>() where TEnum : struct, Enum
            => DefaultMetadata != null ? 
            (TEnum)Convert.ChangeType(DefaultMetadata.TYPE, typeof(TEnum)) :
            (TEnum)Convert.ChangeType(EChunkType.DOCUMENT, typeof(TEnum)); 

        /// <summary>
        /// Helper method to 'convert' a chunk (usually a newly created chunk) to 
        /// the specific type (usually an extended type))
        /// Recieves an int as input to allow inheritance outside the sdk, but the recommended
        /// usage is to create an Enum for your extended chunks / collections and pass the casted value
        /// </summary>
        /// <param name="type"></param>
        public void UpdateType(int type)
        {
            Type = type;
            
            AddMetadata(nameof(ChromaMetadata.TYPE).ToLower(), Type);
            
            if (DefaultMetadata != null)
                DefaultMetadata.TYPE = Type;
        }
        /// <summary>
        /// Add or overrides a Metadata value from the Dictionary (the 'raw' chroma data)
        /// Optionally reserializes the Metadatadictionary to update the Chunk DefaultMetadata class.
        /// Defaulting to false allows to read the 'current' value from the DefaultMetadata class and perform update
        /// operation on the Metadata Dictionary without commiting the result until desired.
        /// </summary>
        /// <param name="key"></param>
        /// <param name="value"></param>
        /// <param name="resetDefault"></param>
        /// <param name="isOverride"></param>
        public void AddMetadata(string key, object value, bool resetDefault = false, bool isOverride = true)
        {
            if (Metadata.ContainsKey(key))
            {
                if (isOverride)
                    Metadata[key] = value;
            }
            else Metadata.Add(key, value);

            if (resetDefault)
                setDefaultMetadata();
        }

        public bool TryRemoveMetadata(string key, bool updateDefault = false)
        {
            if (!HasMetadata(key)) return false;

            if(Metadata.Remove(key))
            {
                if (updateDefault)
                    setDefaultMetadata();

                return true;
            }

            return false;
        }

        public void CloneMetadata(Dictionary<string, object> metadata, bool resetDefault = false)
        {
            var clone = new Dictionary<string, object>();

            foreach (var key in metadata.Keys)
                clone.Add(key, metadata[key]);

            Metadata = clone;

            if (resetDefault)
                setDefaultMetadata();
        }
        public bool HasMetadata(string key) => Metadata != null && Metadata.ContainsKey(key);

        /// <summary>
        /// Abstract method (implementation required in every inherited class)
        /// Handles polymorphism / inheritance deserializing the recieved Metadata Dictionary from Chroma to
        /// the inherited metadata class.
        /// Its called ALWAYS during construcion and using the 'AddMetadata' method with 'resetDefaults = true'
        /// </summary>
        protected abstract void setDefaultMetadata();
       
        /// <summary>
        /// Helper method to get the chunk DefaultMetadata casted to the inherited class
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <returns></returns>
        public T GetMeta<T>() where T : ChromaMetadata
            => (T)DefaultMetadata;
    }
}
